"use strict";
exports.__esModule = true;
var MyClass_1 = require("./MyClass");
var MyClass_2 = require("./MyClass");
var obj1 = new MyClass_1.MyClass();
obj1.foo("John");
var obj2 = new MyClass_1.AnotherClass();
obj2.foo("JameS");
var obj3 = new MyClass_2.MainClass();
obj2.foo("Mary");
